dist: xenial

language: python
python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
  - "3.7-dev"
# command to install dependencies
install:
  - python -m pip install -r requirements_test.txt

# command to run tests
script:
  - python -m pytest --cov=.

after_success:
  - coveralls

sudo: false # route your build to the container-based infrastructure for a faster build

notifications:
  email: false
