#!/bin/bash
pushd examples

echo make venv

python3 -m venv _test_env

echo install requirements

_test_env/bin/python -m pip install -r ../../requirements_test.txt

echo install module

 _test_env/bin/python -m pip install ../../dist/webtest_flask_fixture-0.5.0.tar.gz

echo run tests
pushd test_files

../_test_env/bin/python example_tests.py
